# Basic configurations on OSCD dataset


# Data
dataset: OSCD
num_workers: 0
repeats: 300
subset: val
crop_size: 96


# Optimizer
optimizer: Adam
lr: 0.001
weight_decay: 0.0001
load_optim: False
save_optim: False
sched_on: True
schedulers:
  - name: ExponentialLR
    gamma: 0.95


# Training related
batch_size: 32
num_epochs: 50
resume: ''
anew: False
device: cuda


# Experiment
exp_dir: ../exp/
# tag: ''
# suffix: ''
# DO NOT specify exp_config
debug_on: False
inherit_off: False
log_off: False
track_intvl: 10
tb_on: False
tb_intvl: 15
suffix_off: True
save_on: False
out_dir: ''


# Criterion
criterion: WNLL
weights: 
  - 0.023   # Weight of no-change class
  - 0.977   # Weight of change class


# Model
model: 
out_type: logits2